### PR TITLE
fix(core): cat-select doesn't update properly when using search and c…

### PR DESCRIPTION
**Pull request by emmoldovan**
…licking outside after selection

### CODE REVIEW

**Comment by fynnfeldpausch** [comment]
@emmoldovan Can you please provide more detailed steps to reproduce or attach a video. I am unable to check because I dont really understand the bug

**Comment by emmoldovan** [comment]
[69d72d9c-5e03-4614-8d31-d00c6276d3c9.webm](https://github.com/haiilo/catalyst/assets/89849556/eb80b21d-5362-4fe4-823d-dfba37dab7b9)

**Comment by emmoldovan** [comment]
1. Must be single select
2. Select an option
3. Click outside
4. Delete the selected option (without using the clear button) and then search something
5. Select the new option
6. Click outside (blur the select)
The selection will go back to the previous one

**Comment by fynnfeldpausch** [comment]
Show me later in the daily. I cannot reproduce it 🤷

**Review by fynnfeldpausch — APPROVED** [review]

**Pull request merged**
